parameters:
#    conf_runner_ui.example.class: ConfRunner\Bundle\UiBundle\Example

services:
#    conf_runner_ui.example:
#        class: %conf_runner_ui.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
