<?php

namespace Relhub\WebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReleaseVersionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReleaseVersionRepository extends EntityRepository
{
}
